// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Aria2cStatus retorna informações sobre o aria2c.
 */
export class Aria2cStatus {
    /**
     * Creates a new Aria2cStatus instance.
     * @param {Partial<Aria2cStatus>} [$$source = {}] - The source object to create the Aria2cStatus.
     */
    constructor($$source = {}) {
        if (!("installed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["installed"] = false;
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Aria2cStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Aria2cStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Aria2cStatus(/** @type {Partial<Aria2cStatus>} */($$parsedSource));
    }
}

/**
 * AudioExtractRequest represents an audio extraction request.
 */
export class AudioExtractRequest {
    /**
     * Creates a new AudioExtractRequest instance.
     * @param {Partial<AudioExtractRequest>} [$$source = {}] - The source object to create the AudioExtractRequest.
     */
    constructor($$source = {}) {
        if (!("inputPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["inputPath"] = "";
        }
        if (!("outputDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["outputDir"] = "";
        }
        if (!("format" in $$source)) {
            /**
             * mp3, aac, m4a, flac, wav, ogg, opus
             * @member
             * @type {string}
             */
            this["format"] = "";
        }
        if (!("quality" in $$source)) {
            /**
             * low, medium, high, best
             * @member
             * @type {string}
             */
            this["quality"] = "";
        }
        if (!("customBitrate" in $$source)) {
            /**
             * kbps, overrides quality
             * @member
             * @type {number}
             */
            this["customBitrate"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AudioExtractRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AudioExtractRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AudioExtractRequest(/** @type {Partial<AudioExtractRequest>} */($$parsedSource));
    }
}

/**
 * ConversionResult represents the result of any conversion.
 */
export class ConversionResult {
    /**
     * Creates a new ConversionResult instance.
     * @param {Partial<ConversionResult>} [$$source = {}] - The source object to create the ConversionResult.
     */
    constructor($$source = {}) {
        if (!("outputPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["outputPath"] = "";
        }
        if (!("inputSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["inputSize"] = 0;
        }
        if (!("outputSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["outputSize"] = 0;
        }
        if (!("compression" in $$source)) {
            /**
             * Percentage saved
             * @member
             * @type {number}
             */
            this["compression"] = 0;
        }
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["errorMessage"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConversionResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConversionResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConversionResult(/** @type {Partial<ConversionResult>} */($$parsedSource));
    }
}

/**
 * ImageConvertRequest represents an image conversion request.
 */
export class ImageConvertRequest {
    /**
     * Creates a new ImageConvertRequest instance.
     * @param {Partial<ImageConvertRequest>} [$$source = {}] - The source object to create the ImageConvertRequest.
     */
    constructor($$source = {}) {
        if (!("inputPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["inputPath"] = "";
        }
        if (!("outputDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["outputDir"] = "";
        }
        if (!("format" in $$source)) {
            /**
             * jpg, png, webp, avif, bmp, tiff
             * @member
             * @type {string}
             */
            this["format"] = "";
        }
        if (!("quality" in $$source)) {
            /**
             * 0-100
             * @member
             * @type {number}
             */
            this["quality"] = 0;
        }
        if (!("width" in $$source)) {
            /**
             * 0 = keep original
             * @member
             * @type {number}
             */
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            /**
             * 0 = keep original
             * @member
             * @type {number}
             */
            this["height"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImageConvertRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ImageConvertRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImageConvertRequest(/** @type {Partial<ImageConvertRequest>} */($$parsedSource));
    }
}

/**
 * MediaInfo representa múltiplas mídias (para carrosseis do Instagram).
 */
export class MediaInfo {
    /**
     * Creates a new MediaInfo instance.
     * @param {Partial<MediaInfo>} [$$source = {}] - The source object to create the MediaInfo.
     */
    constructor($$source = {}) {
        if (!("originalUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["originalUrl"] = "";
        }
        if (!("mediaItems" in $$source)) {
            /**
             * @member
             * @type {MediaItemDTO[]}
             */
            this["mediaItems"] = [];
        }
        if (!("source" in $$source)) {
            /**
             * "instagram", "twitter", etc
             * @member
             * @type {string}
             */
            this["source"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MediaInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MediaInfo}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("mediaItems" in $$parsedSource) {
            $$parsedSource["mediaItems"] = $$createField1_0($$parsedSource["mediaItems"]);
        }
        return new MediaInfo(/** @type {Partial<MediaInfo>} */($$parsedSource));
    }
}

/**
 * MediaItemDTO representa uma mídia individual.
 */
export class MediaItemDTO {
    /**
     * Creates a new MediaItemDTO instance.
     * @param {Partial<MediaItemDTO>} [$$source = {}] - The source object to create the MediaItemDTO.
     */
    constructor($$source = {}) {
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * "image" ou "video"
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("width" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["height"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MediaItemDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MediaItemDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MediaItemDTO(/** @type {Partial<MediaItemDTO>} */($$parsedSource));
    }
}

/**
 * VideoConvertRequest represents a video conversion request from frontend.
 */
export class VideoConvertRequest {
    /**
     * Creates a new VideoConvertRequest instance.
     * @param {Partial<VideoConvertRequest>} [$$source = {}] - The source object to create the VideoConvertRequest.
     */
    constructor($$source = {}) {
        if (!("inputPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["inputPath"] = "";
        }
        if (!("outputDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["outputDir"] = "";
        }
        if (!("format" in $$source)) {
            /**
             * mp4, mkv, webm, avi, mov
             * @member
             * @type {string}
             */
            this["format"] = "";
        }
        if (!("quality" in $$source)) {
            /**
             * lossless, high, medium, low, tiny
             * @member
             * @type {string}
             */
            this["quality"] = "";
        }
        if (!("customCrf" in $$source)) {
            /**
             * 0-51, overrides quality
             * @member
             * @type {number}
             */
            this["customCrf"] = 0;
        }
        if (!("preset" in $$source)) {
            /**
             * ultrafast, fast, medium, slow, veryslow
             * @member
             * @type {string}
             */
            this["preset"] = "";
        }
        if (!("resolution" in $$source)) {
            /**
             * e.g. "1920x1080"
             * @member
             * @type {string}
             */
            this["resolution"] = "";
        }
        if (!("keepAudio" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["keepAudio"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VideoConvertRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VideoConvertRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VideoConvertRequest(/** @type {Partial<VideoConvertRequest>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = MediaItemDTO.createFrom;
const $$createType1 = $Create.Array($$createType0);
