// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Config {
    /**
     * Creates a new Config instance.
     * @param {Partial<Config>} [$$source = {}] - The source object to create the Config.
     */
    constructor($$source = {}) {
        if (!("downloadsPath" in $$source)) {
            /**
             * Deprecated: use Video/Image specific paths
             * @member
             * @type {string}
             */
            this["downloadsPath"] = "";
        }
        if (!("videoDownloadPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["videoDownloadPath"] = "";
        }
        if (!("imageDownloadPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["imageDownloadPath"] = "";
        }
        if (!("image" in $$source)) {
            /**
             * @member
             * @type {ImageConfig}
             */
            this["image"] = (new ImageConfig());
        }
        if (!("shortcuts" in $$source)) {
            /**
             * @member
             * @type {ShortcutsConfig}
             */
            this["shortcuts"] = (new ShortcutsConfig());
        }
        if (!("clipboardMonitorEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["clipboardMonitorEnabled"] = false;
        }
        if (!("telemetryEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["telemetryEnabled"] = false;
        }
        if (!("roadmap" in $$source)) {
            /**
             * @member
             * @type {RoadmapConfig}
             */
            this["roadmap"] = (new RoadmapConfig());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Config}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType1;
        const $$createField7_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("image" in $$parsedSource) {
            $$parsedSource["image"] = $$createField3_0($$parsedSource["image"]);
        }
        if ("shortcuts" in $$parsedSource) {
            $$parsedSource["shortcuts"] = $$createField4_0($$parsedSource["shortcuts"]);
        }
        if ("roadmap" in $$parsedSource) {
            $$parsedSource["roadmap"] = $$createField7_0($$parsedSource["roadmap"]);
        }
        return new Config(/** @type {Partial<Config>} */($$parsedSource));
    }
}

export class ImageConfig {
    /**
     * Creates a new ImageConfig instance.
     * @param {Partial<ImageConfig>} [$$source = {}] - The source object to create the ImageConfig.
     */
    constructor($$source = {}) {
        if (!("format" in $$source)) {
            /**
             * original, png, jpg, webp, avif
             * @member
             * @type {string}
             */
            this["format"] = "";
        }
        if (!("quality" in $$source)) {
            /**
             * 0-100 (high is better)
             * @member
             * @type {number}
             */
            this["quality"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImageConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ImageConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImageConfig(/** @type {Partial<ImageConfig>} */($$parsedSource));
    }
}

/**
 * RoadmapConfig holds CDN configuration for the roadmap feature
 */
export class RoadmapConfig {
    /**
     * Creates a new RoadmapConfig instance.
     * @param {Partial<RoadmapConfig>} [$$source = {}] - The source object to create the RoadmapConfig.
     */
    constructor($$source = {}) {
        if (!("cdnEnabled" in $$source)) {
            /**
             * Use CDN instead of direct GitHub API
             * @member
             * @type {boolean}
             */
            this["cdnEnabled"] = false;
        }
        if (!("cdnBaseUrl" in $$source)) {
            /**
             * Base URL for CDN (e.g., "https://downkingo-roadmap.pages.dev")
             * @member
             * @type {string}
             */
            this["cdnBaseUrl"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RoadmapConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RoadmapConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RoadmapConfig(/** @type {Partial<RoadmapConfig>} */($$parsedSource));
    }
}

export class ShortcutsConfig {
    /**
     * Creates a new ShortcutsConfig instance.
     * @param {Partial<ShortcutsConfig>} [$$source = {}] - The source object to create the ShortcutsConfig.
     */
    constructor($$source = {}) {
        if (!("focusInput" in $$source)) {
            /**
             * Default: Ctrl+L
             * @member
             * @type {string}
             */
            this["focusInput"] = "";
        }
        if (!("openSettings" in $$source)) {
            /**
             * Default: Ctrl+,
             * @member
             * @type {string}
             */
            this["openSettings"] = "";
        }
        if (!("openQueue" in $$source)) {
            /**
             * Default: Ctrl+Q
             * @member
             * @type {string}
             */
            this["openQueue"] = "";
        }
        if (!("openHistory" in $$source)) {
            /**
             * Default: Ctrl+H
             * @member
             * @type {string}
             */
            this["openHistory"] = "";
        }
        if (!("openDownloads" in $$source)) {
            /**
             * Default: Ctrl+D
             * @member
             * @type {string}
             */
            this["openDownloads"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ShortcutsConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ShortcutsConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ShortcutsConfig(/** @type {Partial<ShortcutsConfig>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = ImageConfig.createFrom;
const $$createType1 = ShortcutsConfig.createFrom;
const $$createType2 = RoadmapConfig.createFrom;
