// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ImageInfo contém metadados de uma imagem detectada
 */
export class ImageInfo {
    /**
     * Creates a new ImageInfo instance.
     * @param {Partial<ImageInfo>} [$$source = {}] - The source object to create the ImageInfo.
     */
    constructor($$source = {}) {
        if (!("originalUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["originalUrl"] = "";
        }
        if (!("directUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["directUrl"] = "";
        }
        if (!("contentType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["contentType"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("filename" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filename"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImageInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ImageInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImageInfo(/** @type {Partial<ImageInfo>} */($$parsedSource));
    }
}
