// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

/**
 * Download represents a download record in the database
 */
export class Download {
    /**
     * Creates a new Download instance.
     * @param {Partial<Download>} [$$source = {}] - The source object to create the Download.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("thumbnail" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["thumbnail"] = "";
        }
        if (!("duration" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["duration"] = 0;
        }
        if (!("uploader" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["uploader"] = "";
        }
        if (!("format" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["format"] = "";
        }
        if (!("audioOnly" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["audioOnly"] = false;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {DownloadStatus}
             */
            this["status"] = DownloadStatus.$zero;
        }
        if (!("progress" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["progress"] = 0;
        }
        if (!("speed" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["speed"] = "";
        }
        if (!("eta" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["eta"] = "";
        }
        if (!("filePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filePath"] = "";
        }
        if (!("fileSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fileSize"] = 0;
        }
        if (!("errorMessage" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["errorMessage"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["createdAt"] = null;
        }
        if (!("startedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time | null}
             */
            this["startedAt"] = null;
        }
        if (!("completedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time | null}
             */
            this["completedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Download instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Download}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Download(/** @type {Partial<Download>} */($$parsedSource));
    }
}

/**
 * DownloadStatus represents the state of a download
 * @readonly
 * @enum {string}
 */
export const DownloadStatus = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    StatusPending: "pending",
    StatusDownloading: "downloading",
    StatusMerging: "merging",
    StatusCompleted: "completed",
    StatusFailed: "failed",
    StatusCancelled: "cancelled",
};
