// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    DownloadOptions,
    Format,
    VideoInfo
} from "./models.js";

import * as $models from "./models.js";

/**
 * FlexibleInt é um tipo customizado que lida com valores int OU float64 do JSON
 * yt-dlp pode retornar duration como 8.171 (float) ou 8 (int) dependendo do extrator
 * @typedef {$models.FlexibleInt} FlexibleInt
 */

/**
 * Quality é um tipo customizado que lida com valores numéricos ou string do yt-dlp
 * @typedef {$models.Quality} Quality
 */

/**
 * Resolution é um tipo customizado que lida com valores null/string do yt-dlp
 * @typedef {$models.Resolution} Resolution
 */
