// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * DownloadOptions specifies download parameters
 */
export class DownloadOptions {
    /**
     * Creates a new DownloadOptions instance.
     * @param {Partial<DownloadOptions>} [$$source = {}] - The source object to create the DownloadOptions.
     */
    constructor($$source = {}) {
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("format" in $$source)) {
            /**
             * yt-dlp format selector
             * @member
             * @type {string}
             */
            this["format"] = "";
        }
        if (!("audioOnly" in $$source)) {
            /**
             * Extract audio only
             * @member
             * @type {boolean}
             */
            this["audioOnly"] = false;
        }
        if (!("audioFormat" in $$source)) {
            /**
             * mp3, m4a, opus, flac, wav
             * @member
             * @type {string}
             */
            this["audioFormat"] = "";
        }
        if (!("audioBitrate" in $$source)) {
            /**
             * 320, 256, 192, 128, 96
             * @member
             * @type {string}
             */
            this["audioBitrate"] = "";
        }
        if (!("downloadSubtitles" in $$source)) {
            /**
             * Download subtitles
             * @member
             * @type {boolean}
             */
            this["downloadSubtitles"] = false;
        }
        if (!("subtitleLanguage" in $$source)) {
            /**
             * pt-BR, en, es, etc.
             * @member
             * @type {string}
             */
            this["subtitleLanguage"] = "";
        }
        if (!("embedSubtitles" in $$source)) {
            /**
             * Embed subs in video
             * @member
             * @type {boolean}
             */
            this["embedSubtitles"] = false;
        }
        if (!("remuxVideo" in $$source)) {
            /**
             * New Options
             * Remux to mp4/mkv
             * @member
             * @type {boolean}
             */
            this["remuxVideo"] = false;
        }
        if (!("remuxFormat" in $$source)) {
            /**
             * mp4, mkv (default mp4)
             * @member
             * @type {string}
             */
            this["remuxFormat"] = "";
        }
        if (!("embedThumbnail" in $$source)) {
            /**
             * Embed thumb in video file
             * @member
             * @type {boolean}
             */
            this["embedThumbnail"] = false;
        }
        if (!("skipExisting" in $$source)) {
            /**
             * Skip if file exists
             * @member
             * @type {boolean}
             */
            this["skipExisting"] = false;
        }
        if (!("incognito" in $$source)) {
            /**
             * Do not save history
             * @member
             * @type {boolean}
             */
            this["incognito"] = false;
        }
        if (!("useAria2c" in $$source)) {
            /**
             * Use aria2c for multi-thread download
             * @member
             * @type {boolean}
             */
            this["useAria2c"] = false;
        }
        if (!("aria2cConnections" in $$source)) {
            /**
             * Number of connections (default 16)
             * @member
             * @type {number}
             */
            this["aria2cConnections"] = 0;
        }
        if (!("title" in $$source)) {
            /**
             * Optional metadata
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("thumbnail" in $$source)) {
            /**
             * Optional metadata
             * @member
             * @type {string}
             */
            this["thumbnail"] = "";
        }
        if (!("startTime" in $$source)) {
            /**
             * Trimmer: cortar trecho do vídeo
             * HH:MM:SS or MM:SS (início do corte)
             * @member
             * @type {string}
             */
            this["startTime"] = "";
        }
        if (!("endTime" in $$source)) {
            /**
             * HH:MM:SS or MM:SS (fim do corte)
             * @member
             * @type {string}
             */
            this["endTime"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DownloadOptions instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DownloadOptions}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DownloadOptions(/** @type {Partial<DownloadOptions>} */($$parsedSource));
    }
}

/**
 * FlexibleInt é um tipo customizado que lida com valores int OU float64 do JSON
 * yt-dlp pode retornar duration como 8.171 (float) ou 8 (int) dependendo do extrator
 * @typedef {number} FlexibleInt
 */

/**
 * Format represents an available video format
 * Usa tipos customizados para lidar com inconsistências do JSON do yt-dlp
 */
export class Format {
    /**
     * Creates a new Format instance.
     * @param {Partial<Format>} [$$source = {}] - The source object to create the Format.
     */
    constructor($$source = {}) {
        if (!("format_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["format_id"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * Direct media URL
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("ext" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ext"] = "";
        }
        if (!("resolution" in $$source)) {
            /**
             * @member
             * @type {Resolution}
             */
            this["resolution"] = "";
        }
        if (!("filesize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["filesize"] = 0;
        }
        if (!("vcodec" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vcodec"] = "";
        }
        if (!("acodec" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["acodec"] = "";
        }
        if (!("quality" in $$source)) {
            /**
             * @member
             * @type {Quality}
             */
            this["quality"] = "";
        }
        if (!("height" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["height"] = 0;
        }
        if (!("width" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["width"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Format instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Format}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Format(/** @type {Partial<Format>} */($$parsedSource));
    }
}

/**
 * Quality é um tipo customizado que lida com valores numéricos ou string do yt-dlp
 * @typedef {string} Quality
 */

/**
 * Resolution é um tipo customizado que lida com valores null/string do yt-dlp
 * @typedef {string} Resolution
 */

/**
 * VideoInfo holds metadata about a video
 */
export class VideoInfo {
    /**
     * Creates a new VideoInfo instance.
     * @param {Partial<VideoInfo>} [$$source = {}] - The source object to create the VideoInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * Direct URL if available (e.g. images)
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("duration" in $$source)) {
            /**
             * @member
             * @type {FlexibleInt}
             */
            this["duration"] = 0;
        }
        if (!("thumbnail" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["thumbnail"] = "";
        }
        if (!("uploader" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["uploader"] = "";
        }
        if (!("view_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["view_count"] = 0;
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("width" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["height"] = 0;
        }
        if (!("formats" in $$source)) {
            /**
             * @member
             * @type {Format[]}
             */
            this["formats"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VideoInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VideoInfo}
     */
    static createFrom($$source = {}) {
        const $$createField10_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("formats" in $$parsedSource) {
            $$parsedSource["formats"] = $$createField10_0($$parsedSource["formats"]);
        }
        return new VideoInfo(/** @type {Partial<VideoInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Format.createFrom;
const $$createType1 = $Create.Array($$createType0);
