// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * CaptionOptions controls subtitle acquisition and visual rendering.
 */
export class CaptionOptions {
    /**
     * Creates a new CaptionOptions instance.
     * @param {Partial<CaptionOptions>} [$$source = {}] - The source object to create the CaptionOptions.
     */
    constructor($$source = {}) {
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("source" in $$source)) {
            /**
             * auto, youtube, whisper
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("language" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["language"] = "";
        }
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model"] = "";
        }
        if (!("cues" in $$source)) {
            /**
             * @member
             * @type {SubtitleCue[]}
             */
            this["cues"] = [];
        }
        if (!("style" in $$source)) {
            /**
             * @member
             * @type {SubtitleStyle}
             */
            this["style"] = (new SubtitleStyle());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CaptionOptions instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CaptionOptions}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("cues" in $$parsedSource) {
            $$parsedSource["cues"] = $$createField4_0($$parsedSource["cues"]);
        }
        if ("style" in $$parsedSource) {
            $$parsedSource["style"] = $$createField5_0($$parsedSource["style"]);
        }
        return new CaptionOptions(/** @type {Partial<CaptionOptions>} */($$parsedSource));
    }
}

export class CutRange {
    /**
     * Creates a new CutRange instance.
     * @param {Partial<CutRange>} [$$source = {}] - The source object to create the CutRange.
     */
    constructor($$source = {}) {
        if (!("start" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["start"] = 0;
        }
        if (!("end" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["end"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CutRange instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CutRange}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CutRange(/** @type {Partial<CutRange>} */($$parsedSource));
    }
}

/**
 * DownloadOptions specifies download parameters
 */
export class DownloadOptions {
    /**
     * Creates a new DownloadOptions instance.
     * @param {Partial<DownloadOptions>} [$$source = {}] - The source object to create the DownloadOptions.
     */
    constructor($$source = {}) {
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("format" in $$source)) {
            /**
             * yt-dlp format selector
             * @member
             * @type {string}
             */
            this["format"] = "";
        }
        if (!("audioOnly" in $$source)) {
            /**
             * Extract audio only
             * @member
             * @type {boolean}
             */
            this["audioOnly"] = false;
        }
        if (!("audioFormat" in $$source)) {
            /**
             * mp3, m4a, opus, flac, wav
             * @member
             * @type {string}
             */
            this["audioFormat"] = "";
        }
        if (!("audioBitrate" in $$source)) {
            /**
             * 320, 256, 192, 128, 96
             * @member
             * @type {string}
             */
            this["audioBitrate"] = "";
        }
        if (!("downloadSubtitles" in $$source)) {
            /**
             * Download subtitles
             * @member
             * @type {boolean}
             */
            this["downloadSubtitles"] = false;
        }
        if (!("subtitleLanguage" in $$source)) {
            /**
             * pt-BR, en, es, etc.
             * @member
             * @type {string}
             */
            this["subtitleLanguage"] = "";
        }
        if (!("embedSubtitles" in $$source)) {
            /**
             * Embed subs in video
             * @member
             * @type {boolean}
             */
            this["embedSubtitles"] = false;
        }
        if (!("remuxVideo" in $$source)) {
            /**
             * New Options
             * Remux to mp4/mkv
             * @member
             * @type {boolean}
             */
            this["remuxVideo"] = false;
        }
        if (!("remuxFormat" in $$source)) {
            /**
             * mp4, mkv (default mp4)
             * @member
             * @type {string}
             */
            this["remuxFormat"] = "";
        }
        if (!("embedThumbnail" in $$source)) {
            /**
             * Embed thumb in video file
             * @member
             * @type {boolean}
             */
            this["embedThumbnail"] = false;
        }
        if (!("skipExisting" in $$source)) {
            /**
             * Skip if file exists
             * @member
             * @type {boolean}
             */
            this["skipExisting"] = false;
        }
        if (!("incognito" in $$source)) {
            /**
             * Do not save history
             * @member
             * @type {boolean}
             */
            this["incognito"] = false;
        }
        if (!("useAria2c" in $$source)) {
            /**
             * Use aria2c for multi-thread download
             * @member
             * @type {boolean}
             */
            this["useAria2c"] = false;
        }
        if (!("aria2cConnections" in $$source)) {
            /**
             * Number of connections (default 16)
             * @member
             * @type {number}
             */
            this["aria2cConnections"] = 0;
        }
        if (!("concurrentFragments" in $$source)) {
            /**
             * Parallel DASH/HLS fragments (default 8)
             * @member
             * @type {number}
             */
            this["concurrentFragments"] = 0;
        }
        if (!("title" in $$source)) {
            /**
             * Optional metadata
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("thumbnail" in $$source)) {
            /**
             * Optional metadata
             * @member
             * @type {string}
             */
            this["thumbnail"] = "";
        }
        if (!("cookieBrowser" in $$source)) {
            /**
             * Browser session explicitly authorized by the user
             * @member
             * @type {string}
             */
            this["cookieBrowser"] = "";
        }
        if (!("startTime" in $$source)) {
            /**
             * Trimmer: cortar trecho do vídeo
             * HH:MM:SS or MM:SS (início do corte)
             * @member
             * @type {string}
             */
            this["startTime"] = "";
        }
        if (!("endTime" in $$source)) {
            /**
             * HH:MM:SS or MM:SS (fim do corte)
             * @member
             * @type {string}
             */
            this["endTime"] = "";
        }
        if (!("excludedRanges" in $$source)) {
            /**
             * Edit decision list: source ranges that must be removed and ripple-joined.
             * @member
             * @type {CutRange[]}
             */
            this["excludedRanges"] = [];
        }
        if (!("captions" in $$source)) {
            /**
             * Captions are visually burned into the rendered video. This is separate
             * from EmbedSubtitles, which only adds a selectable subtitle stream.
             * @member
             * @type {CaptionOptions}
             */
            this["captions"] = (new CaptionOptions());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DownloadOptions instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DownloadOptions}
     */
    static createFrom($$source = {}) {
        const $$createField21_0 = $$createType4;
        const $$createField22_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("excludedRanges" in $$parsedSource) {
            $$parsedSource["excludedRanges"] = $$createField21_0($$parsedSource["excludedRanges"]);
        }
        if ("captions" in $$parsedSource) {
            $$parsedSource["captions"] = $$createField22_0($$parsedSource["captions"]);
        }
        return new DownloadOptions(/** @type {Partial<DownloadOptions>} */($$parsedSource));
    }
}

/**
 * FlexibleInt é um tipo customizado que lida com valores int OU float64 do JSON
 * yt-dlp pode retornar duration como 8.171 (float) ou 8 (int) dependendo do extrator
 * @typedef {number} FlexibleInt
 */

/**
 * Format represents an available video format
 * Usa tipos customizados para lidar com inconsistências do JSON do yt-dlp
 */
export class Format {
    /**
     * Creates a new Format instance.
     * @param {Partial<Format>} [$$source = {}] - The source object to create the Format.
     */
    constructor($$source = {}) {
        if (!("format_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["format_id"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * Direct media URL
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("ext" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ext"] = "";
        }
        if (!("resolution" in $$source)) {
            /**
             * @member
             * @type {Resolution}
             */
            this["resolution"] = "";
        }
        if (!("filesize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["filesize"] = 0;
        }
        if (!("vcodec" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vcodec"] = "";
        }
        if (!("acodec" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["acodec"] = "";
        }
        if (!("quality" in $$source)) {
            /**
             * @member
             * @type {Quality}
             */
            this["quality"] = "";
        }
        if (!("height" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["height"] = 0;
        }
        if (!("width" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["width"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Format instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Format}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Format(/** @type {Partial<Format>} */($$parsedSource));
    }
}

/**
 * Quality é um tipo customizado que lida com valores numéricos ou string do yt-dlp
 * @typedef {string} Quality
 */

/**
 * Resolution é um tipo customizado que lida com valores null/string do yt-dlp
 * @typedef {string} Resolution
 */

/**
 * SubtitleCue is one editable, timestamped caption in source-video time.
 */
export class SubtitleCue {
    /**
     * Creates a new SubtitleCue instance.
     * @param {Partial<SubtitleCue>} [$$source = {}] - The source object to create the SubtitleCue.
     */
    constructor($$source = {}) {
        if (!("start" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["start"] = 0;
        }
        if (!("end" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["end"] = 0;
        }
        if (!("text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["text"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SubtitleCue instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SubtitleCue}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SubtitleCue(/** @type {Partial<SubtitleCue>} */($$parsedSource));
    }
}

/**
 * SubtitleLanguage is a caption language advertised by the extractor. Source
 * is either "manual" or "automatic"; a manual track wins when both exist.
 */
export class SubtitleLanguage {
    /**
     * Creates a new SubtitleLanguage instance.
     * @param {Partial<SubtitleLanguage>} [$$source = {}] - The source object to create the SubtitleLanguage.
     */
    constructor($$source = {}) {
        if (!("code" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["code"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SubtitleLanguage instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SubtitleLanguage}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SubtitleLanguage(/** @type {Partial<SubtitleLanguage>} */($$parsedSource));
    }
}

/**
 * SubtitleResult is returned to the editor after importing a remote track.
 */
export class SubtitleResult {
    /**
     * Creates a new SubtitleResult instance.
     * @param {Partial<SubtitleResult>} [$$source = {}] - The source object to create the SubtitleResult.
     */
    constructor($$source = {}) {
        if (!("cues" in $$source)) {
            /**
             * @member
             * @type {SubtitleCue[]}
             */
            this["cues"] = [];
        }
        if (!("language" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["language"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SubtitleResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SubtitleResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("cues" in $$parsedSource) {
            $$parsedSource["cues"] = $$createField0_0($$parsedSource["cues"]);
        }
        return new SubtitleResult(/** @type {Partial<SubtitleResult>} */($$parsedSource));
    }
}

/**
 * SubtitleStyle maps the editor controls to an ASS style rendered by FFmpeg.
 */
export class SubtitleStyle {
    /**
     * Creates a new SubtitleStyle instance.
     * @param {Partial<SubtitleStyle>} [$$source = {}] - The source object to create the SubtitleStyle.
     */
    constructor($$source = {}) {
        if (!("fontFamily" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fontFamily"] = "";
        }
        if (!("fontSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fontSize"] = 0;
        }
        if (!("textColor" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["textColor"] = "";
        }
        if (!("backgroundColor" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["backgroundColor"] = "";
        }
        if (!("backgroundOpacity" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["backgroundOpacity"] = 0;
        }
        if (!("outlineColor" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["outlineColor"] = "";
        }
        if (!("outlineWidth" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["outlineWidth"] = 0;
        }
        if (!("position" in $$source)) {
            /**
             * top, center, bottom
             * @member
             * @type {string}
             */
            this["position"] = "";
        }
        if (!("bold" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["bold"] = false;
        }
        if (!("italic" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["italic"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SubtitleStyle instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SubtitleStyle}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SubtitleStyle(/** @type {Partial<SubtitleStyle>} */($$parsedSource));
    }
}

/**
 * Thumbnail is one image candidate emitted by yt-dlp.
 */
export class Thumbnail {
    /**
     * Creates a new Thumbnail instance.
     * @param {Partial<Thumbnail>} [$$source = {}] - The source object to create the Thumbnail.
     */
    constructor($$source = {}) {
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("width" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["height"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Thumbnail instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Thumbnail}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Thumbnail(/** @type {Partial<Thumbnail>} */($$parsedSource));
    }
}

/**
 * VideoInfo holds metadata about a video
 */
export class VideoInfo {
    /**
     * Creates a new VideoInfo instance.
     * @param {Partial<VideoInfo>} [$$source = {}] - The source object to create the VideoInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * Direct URL if available (e.g. images)
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("duration" in $$source)) {
            /**
             * @member
             * @type {FlexibleInt}
             */
            this["duration"] = 0;
        }
        if (!("thumbnail" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["thumbnail"] = "";
        }
        if (!("thumbnails" in $$source)) {
            /**
             * @member
             * @type {Thumbnail[]}
             */
            this["thumbnails"] = [];
        }
        if (!("uploader" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["uploader"] = "";
        }
        if (!("view_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["view_count"] = 0;
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("language" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["language"] = "";
        }
        if (!("width" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["height"] = 0;
        }
        if (!("formats" in $$source)) {
            /**
             * @member
             * @type {Format[]}
             */
            this["formats"] = [];
        }
        if (!("subtitle_languages" in $$source)) {
            /**
             * @member
             * @type {SubtitleLanguage[]}
             */
            this["subtitle_languages"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["cookie_browser"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VideoInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VideoInfo}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType7;
        const $$createField12_0 = $$createType9;
        const $$createField13_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("thumbnails" in $$parsedSource) {
            $$parsedSource["thumbnails"] = $$createField5_0($$parsedSource["thumbnails"]);
        }
        if ("formats" in $$parsedSource) {
            $$parsedSource["formats"] = $$createField12_0($$parsedSource["formats"]);
        }
        if ("subtitle_languages" in $$parsedSource) {
            $$parsedSource["subtitle_languages"] = $$createField13_0($$parsedSource["subtitle_languages"]);
        }
        return new VideoInfo(/** @type {Partial<VideoInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = SubtitleCue.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = SubtitleStyle.createFrom;
const $$createType3 = CutRange.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = CaptionOptions.createFrom;
const $$createType6 = Thumbnail.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = Format.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = SubtitleLanguage.createFrom;
const $$createType11 = $Create.Array($$createType10);
