// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class DeviceCodeResponse {
    /**
     * Creates a new DeviceCodeResponse instance.
     * @param {Partial<DeviceCodeResponse>} [$$source = {}] - The source object to create the DeviceCodeResponse.
     */
    constructor($$source = {}) {
        if (!("device_code" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["device_code"] = "";
        }
        if (!("user_code" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["user_code"] = "";
        }
        if (!("verification_uri" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["verification_uri"] = "";
        }
        if (!("expires_in" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["expires_in"] = 0;
        }
        if (!("interval" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["interval"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeviceCodeResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DeviceCodeResponse}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeviceCodeResponse(/** @type {Partial<DeviceCodeResponse>} */($$parsedSource));
    }
}
