// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct is the Facade that exposes methods to the Frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {
  Call as $Call,
  CancellablePromise as $CancellablePromise,
  Create as $Create,
} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as auth$0 from "./internal/auth/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "./internal/config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as handlers$0 from "./internal/handlers/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as images$0 from "./internal/images/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as launcher$0 from "./internal/launcher/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as roadmap$0 from "./internal/roadmap/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as storage$0 from "./internal/storage/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as updater$0 from "./internal/updater/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as whisper$0 from "./internal/whisper/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as youtube$0 from "./internal/youtube/models.js";

/**
 * @param {string} url
 * @param {string} format
 * @param {boolean} audioOnly
 * @returns {$CancellablePromise<storage$0.Download | null>}
 */
export function AddToQueue(url, format, audioOnly) {
  return $Call.ByID(2602362584, url, format, audioOnly).then(
    /** @type {($result: any) => any} */ (
      ($result) => {
        return $$createType1($result);
      }
    ),
  );
}

/**
 * @param {youtube$0.DownloadOptions} opts
 * @returns {$CancellablePromise<storage$0.Download | null>}
 */
export function AddToQueueAdvanced(opts) {
  return $Call.ByID(788105866, opts).then(
    /** @type {($result: any) => any} */ (
      ($result) => {
        return $$createType1($result);
      }
    ),
  );
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function CancelDownload(id) {
  return $Call.ByID(2532515671, id);
}

/**
 * @returns {$CancellablePromise<handlers$0.Aria2cStatus>}
 */
export function CheckAria2cStatus() {
  return $Call.ByID(1529744055).then(
    /** @type {($result: any) => any} */ (
      ($result) => {
        return $$createType2($result);
      }
    ),
  );
}

/**
 * @returns {$CancellablePromise<launcher$0.DependencyStatus[]>}
 */
export function CheckDependencies() {
  return $Call.ByID(494838570).then(
    /** @type {($result: any) => any} */ (
      ($result) => {
        return $$createType4($result);
      }
    ),
  );
}

/**
 * @returns {$CancellablePromise<updater$0.UpdateInfo | null>}
 */
export function CheckForUpdate() {
  return $Call.ByID(2347956003).then(
    /** @type {($result: any) => any} */ (
      ($result) => {
        return $$createType6($result);
      }
    ),
  );
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ClearDownloadHistory() {
  return $Call.ByID(3929121706);
}

/**
 * @param {string} inputPath
 * @param {number} quality
 * @returns {$CancellablePromise<handlers$0.ConversionResult | null>}
 */
export function CompressImage(inputPath, quality) {
  return $Call.ByID(2469861642, inputPath, quality).then(
    /** @type {($result: any) => any} */ (
      ($result) => {
        return $$createType8($result);
      }
    ),
  );
}

/**
 * @param {string} inputPath
 * @param {string} quality
 * @param {string} preset
 * @returns {$CancellablePromise<handlers$0.ConversionResult | null>}
 */
export function CompressVideo(inputPath, quality, preset) {
  return $Call.ByID(2079159196, inputPath, quality, preset).then(
    /** @type {($result: any) => any} */ (
      ($result) => {
        return $$createType8($result);
      }
    ),
  );
}

/**
 * @param {handlers$0.ImageConvertRequest} req
 * @returns {$CancellablePromise<handlers$0.ConversionResult | null>}
 */
export function ConvertImage(req) {
  return $Call.ByID(108711885, req).then(
    /** @type {($result: any) => any} */ (
      ($result) => {
        return $$createType8($result);
      }
    ),
  );
}

/**
 * @param {handlers$0.VideoConvertRequest} req
 * @returns {$CancellablePromise<handlers$0.ConversionResult | null>}
 */
export function ConvertVideo(req) {
  return $Call.ByID(224996083, req).then(
    /** @type {($result: any) => any} */ (
      ($result) => {
        return $$createType8($result);
      }
    ),
  );
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function DeleteAria2c() {
  return $Call.ByID(3140778760);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function DeleteWhisperModel(name) {
  return $Call.ByID(111941057, name);
}

/**
 * @param {youtube$0.DownloadOptions} opts
 * @returns {$CancellablePromise<void>}
 */
export function Download(opts) {
  return $Call.ByID(2709798689, opts);
}

/**
 * @param {string} downloadURL
 * @returns {$CancellablePromise<void>}
 */
export function DownloadAndApplyUpdate(downloadURL) {
  return $Call.ByID(714979995, downloadURL);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function DownloadAria2c() {
  return $Call.ByID(2716593299);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function DownloadDependencies() {
  return $Call.ByID(1006649596);
}

/**
 * @param {string} url
 * @param {string} filename
 * @returns {$CancellablePromise<string>}
 */
export function DownloadImage(url, filename) {
  return $Call.ByID(1200166230, url, filename);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function DownloadWhisperBinary() {
  return $Call.ByID(4064086400);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function DownloadWhisperModel(name) {
  return $Call.ByID(250633958, name);
}

/**
 * @param {handlers$0.AudioExtractRequest} req
 * @returns {$CancellablePromise<handlers$0.ConversionResult | null>}
 */
export function ExtractAudio(req) {
  return $Call.ByID(150980096, req).then(
    /** @type {($result: any) => any} */ (
      ($result) => {
        return $$createType8($result);
      }
    ),
  );
}

/**
 * @param {string} text
 * @returns {$CancellablePromise<void>}
 */
export function ExportTranscriptionDOCX(text) {
  return $Call.ByName("main.App.ExportTranscriptionDOCX", text);
}

/**
 * @returns {$CancellablePromise<updater$0.Release[]>}
 */
export function GetAvailableAppVersions() {
  return $Call.ByID(2485740604).then(
    /** @type {($result: any) => any} */ (
      ($result) => {
        return $$createType10($result);
      }
    ),
  );
}

/**
 * @returns {$CancellablePromise<whisper$0.AvailableModel[]>}
 */
export function GetAvailableWhisperModels() {
  return $Call.ByID(1348308402).then(
    /** @type {($result: any) => any} */ (
      ($result) => {
        return $$createType12($result);
      }
    ),
  );
}

/**
 * @param {number} limit
 * @returns {$CancellablePromise<(storage$0.Download | null)[]>}
 */
export function GetDownloadHistory(limit) {
  return $Call.ByID(863967493, limit).then(
    /** @type {($result: any) => any} */ (
      ($result) => {
        return $$createType13($result);
      }
    ),
  );
}

/**
 * @returns {$CancellablePromise<(storage$0.Download | null)[]>}
 */
export function GetDownloadQueue() {
  return $Call.ByID(2432386474).then(
    /** @type {($result: any) => any} */ (
      ($result) => {
        return $$createType13($result);
      }
    ),
  );
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetDownloadsPath() {
  return $Call.ByID(3773782479);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetGitHubToken() {
  return $Call.ByID(2176877497);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetImageDownloadPath() {
  return $Call.ByID(1710355803);
}

/**
 * @param {string} url
 * @returns {$CancellablePromise<images$0.ImageInfo | null>}
 */
export function GetImageInfo(url) {
  return $Call.ByID(3625829128, url).then(
    /** @type {($result: any) => any} */ (
      ($result) => {
        return $$createType15($result);
      }
    ),
  );
}

/**
 * @param {string} url
 * @returns {$CancellablePromise<handlers$0.MediaInfo | null>}
 */
export function GetInstagramCarousel(url) {
  return $Call.ByID(881087455, url).then(
    /** @type {($result: any) => any} */ (
      ($result) => {
        return $$createType17($result);
      }
    ),
  );
}

/**
 * GetRoadmap fetches roadmap items from the configured source
 * @param {string} lang
 * @returns {$CancellablePromise<roadmap$0.RoadmapItem[]>}
 */
export function GetRoadmap(lang) {
  return $Call.ByID(3740686969, lang).then(
    /** @type {($result: any) => any} */ (
      ($result) => {
        return $$createType19($result);
      }
    ),
  );
}

/**
 * @returns {$CancellablePromise<config$0.Config>}
 */
export function GetSettings() {
  return $Call.ByID(2554697378).then(
    /** @type {($result: any) => any} */ (
      ($result) => {
        return $$createType20($result);
      }
    ),
  );
}

/**
 * GetUserReaction returns the user's current reaction on a specific issue
 * Returns "+1" for thumbs up, "-1" for thumbs down, or "" for no reaction
 * @param {number} issueID
 * @returns {$CancellablePromise<string>}
 */
export function GetUserReaction(issueID) {
  return $Call.ByID(3424788871, issueID);
}

/**
 * GetUserReactions returns a map of issue IDs to user's reaction for syncing with frontend
 * This fetches reactions for all roadmap items at once
 * @returns {$CancellablePromise<{ [_ in `${number}`]?: string }>}
 */
export function GetUserReactions() {
  return $Call.ByID(1304130332).then(
    /** @type {($result: any) => any} */ (
      ($result) => {
        return $$createType21($result);
      }
    ),
  );
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetVersion() {
  return $Call.ByID(1049863377);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetVideoDownloadPath() {
  return $Call.ByID(336675393);
}

/**
 * GetStreamURL extracts the stream URL and returns a local proxy URL for the frontend.
 * Returns the proxy URL (http://127.0.0.1:PORT/proxy/stream) for CORS-free video preview.
 * @param {string} url
 * @param {string} format
 * @returns {$CancellablePromise<string>}
 */
export function GetStreamURL(url, format) {
  return $Call.ByName("main.App.GetStreamURL", url, format);
}

/**
 * SetStreamURL registers a direct stream URL in the proxy without invoking yt-dlp.
 * Instant alternative to GetStreamURL when the frontend already has the stream URL.
 * @param {string} directURL
 * @returns {$CancellablePromise<string>}
 */
export function SetStreamURL(directURL) {
  return $Call.ByName("main.App.SetStreamURL", directURL);
}

/**
 * GetVideoInfo delegates to videoHandler
 * @param {string} url
 * @returns {$CancellablePromise<youtube$0.VideoInfo | null>}
 */
export function GetVideoInfo(url) {
  return $Call.ByID(545710026, url).then(
    /** @type {($result: any) => any} */ (
      ($result) => {
        return $$createType23($result);
      }
    ),
  );
}

/**
 * @param {string} tag
 * @returns {$CancellablePromise<void>}
 */
export function InstallAppVersion(tag) {
  return $Call.ByID(3982740749, tag);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function IsWhisperInstalled() {
  return $Call.ByID(444764833);
}

/**
 * @returns {$CancellablePromise<whisper$0.ModelInfo[]>}
 */
export function ListWhisperModels() {
  return $Call.ByID(1479260439).then(
    /** @type {($result: any) => any} */ (
      ($result) => {
        return $$createType25($result);
      }
    ),
  );
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function LogoutGitHub() {
  return $Call.ByID(2536661304);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function NeedsDependencies() {
  return $Call.ByID(4002180015);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function OpenDownloadFolder(id) {
  return $Call.ByID(4103450229, id);
}

/**
 * @param {string} url
 * @returns {$CancellablePromise<void>}
 */
export function OpenUrl(url) {
  return $Call.ByID(4116595874, url);
}

/**
 * PollGitHubAuth polls until user authorizes (or timeout)
 * @param {string} deviceCode
 * @returns {$CancellablePromise<string>}
 */
export function PollGitHubAuth(deviceCode) {
  return $Call.ByID(1729214153, deviceCode);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function RestartApp() {
  return $Call.ByID(4246341431);
}

/**
 * @param {config$0.Config | null} newCfg
 * @returns {$CancellablePromise<void>}
 */
export function SaveSettings(newCfg) {
  return $Call.ByID(1949631069, newCfg);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function SelectDirectory() {
  return $Call.ByID(1735672136);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function SelectImageDirectory() {
  return $Call.ByID(4161598873);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function SelectImageFile() {
  return $Call.ByID(4262026332);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function SelectMediaFile() {
  return $Call.ByID(2449334365);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function SelectOutputDirectory() {
  return $Call.ByID(2051919695);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function SelectVideoDirectory() {
  return $Call.ByID(945514935);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function SelectVideoFile() {
  return $Call.ByID(532478010);
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function SelectVideoFiles() {
  return $Call.ByName("main.App.SelectVideoFiles");
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function SelectImageFiles() {
  return $Call.ByName("main.App.SelectImageFiles");
}

/**
 * @param {string} inputPath
 * @param {number} maxSize
 * @returns {$CancellablePromise<string>}
 */
export function ReadImageThumbnail(inputPath, maxSize) {
  return $Call.ByName("main.App.ReadImageThumbnail", inputPath, maxSize);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<number>}
 */
export function GetFileSize(path) {
  return $Call.ByName("main.App.GetFileSize", path);
}

/**
 * SetClipboardMonitor enables or disables the clipboard monitoring
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetClipboardMonitor(enabled) {
  return $Call.ByID(2247635427, enabled);
}

/**
 * StartGitHubAuth initiates Device Flow and returns user code + verification URL
 * @returns {$CancellablePromise<auth$0.DeviceCodeResponse | null>}
 */
export function StartGitHubAuth() {
  return $Call.ByID(4217852034).then(
    /** @type {($result: any) => any} */ (
      ($result) => {
        return $$createType27($result);
      }
    ),
  );
}

/**
 * @param {string} title
 * @param {string} desc
 * @returns {$CancellablePromise<void>}
 */
export function SuggestFeature(title, desc) {
  return $Call.ByID(2695915429, title, desc);
}

/**
 * @param {handlers$0.TranscribeRequest} req
 * @returns {$CancellablePromise<whisper$0.TranscribeResult | null>}
 */
export function TranscribeFile(req) {
  return $Call.ByID(1827659560, req).then(
    /** @type {($result: any) => any} */ (
      ($result) => {
        return $$createType29($result);
      }
    ),
  );
}

/**
 * @param {string} channel
 * @returns {$CancellablePromise<string>}
 */
export function UpdateYtDlp(channel) {
  return $Call.ByID(461922123, channel);
}

/**
 * @param {number} issueID
 * @returns {$CancellablePromise<void>}
 */
export function VoteDownFeature(issueID) {
  return $Call.ByID(1033779589, issueID);
}

/**
 * @param {number} issueID
 * @returns {$CancellablePromise<void>}
 */
export function VoteFeature(issueID) {
  return $Call.ByID(210585845, issueID);
}

// Private type creation functions
const $$createType0 = storage$0.Download.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = handlers$0.Aria2cStatus.createFrom;
const $$createType3 = launcher$0.DependencyStatus.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = updater$0.UpdateInfo.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = handlers$0.ConversionResult.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = updater$0.Release.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = whisper$0.AvailableModel.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = $Create.Array($$createType1);
const $$createType14 = images$0.ImageInfo.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = handlers$0.MediaInfo.createFrom;
const $$createType17 = $Create.Nullable($$createType16);
const $$createType18 = roadmap$0.RoadmapItem.createFrom;
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = config$0.Config.createFrom;
const $$createType21 = $Create.Map($Create.Any, $Create.Any);
const $$createType22 = youtube$0.VideoInfo.createFrom;
const $$createType23 = $Create.Nullable($$createType22);
const $$createType24 = whisper$0.ModelInfo.createFrom;
const $$createType25 = $Create.Array($$createType24);
const $$createType26 = auth$0.DeviceCodeResponse.createFrom;
const $$createType27 = $Create.Nullable($$createType26);
const $$createType28 = whisper$0.TranscribeResult.createFrom;
const $$createType29 = $Create.Nullable($$createType28);
