// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AvailableModel describes a model available for download.
 */
export class AvailableModel {
    /**
     * Creates a new AvailableModel instance.
     * @param {Partial<AvailableModel>} [$$source = {}] - The source object to create the AvailableModel.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["size"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AvailableModel instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AvailableModel}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AvailableModel(/** @type {Partial<AvailableModel>} */($$parsedSource));
    }
}

/**
 * ModelInfo holds metadata about a whisper model.
 */
export class ModelInfo {
    /**
     * Creates a new ModelInfo instance.
     * @param {Partial<ModelInfo>} [$$source = {}] - The source object to create the ModelInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ModelInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModelInfo(/** @type {Partial<ModelInfo>} */($$parsedSource));
    }
}

/**
 * Segment represents a timestamped segment of transcription.
 */
export class Segment {
    /**
     * Creates a new Segment instance.
     * @param {Partial<Segment>} [$$source = {}] - The source object to create the Segment.
     */
    constructor($$source = {}) {
        if (!("start" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["start"] = 0;
        }
        if (!("end" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["end"] = 0;
        }
        if (!("text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["text"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Segment instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Segment}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Segment(/** @type {Partial<Segment>} */($$parsedSource));
    }
}

/**
 * TranscribeResult holds the result of a transcription.
 */
export class TranscribeResult {
    /**
     * Creates a new TranscribeResult instance.
     * @param {Partial<TranscribeResult>} [$$source = {}] - The source object to create the TranscribeResult.
     */
    constructor($$source = {}) {
        if (!("text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["text"] = "";
        }
        if (!("segments" in $$source)) {
            /**
             * @member
             * @type {Segment[]}
             */
            this["segments"] = [];
        }
        if (!("language" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["language"] = "";
        }
        if (!("duration" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["duration"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TranscribeResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TranscribeResult}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("segments" in $$parsedSource) {
            $$parsedSource["segments"] = $$createField1_0($$parsedSource["segments"]);
        }
        return new TranscribeResult(/** @type {Partial<TranscribeResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Segment.createFrom;
const $$createType1 = $Create.Array($$createType0);
