// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Asset represents a release asset
 */
export class Asset {
    /**
     * Creates a new Asset instance.
     * @param {Partial<Asset>} [$$source = {}] - The source object to create the Asset.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("browser_download_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["browser_download_url"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Asset instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Asset}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Asset(/** @type {Partial<Asset>} */($$parsedSource));
    }
}

/**
 * Release represents a GitHub release
 */
export class Release {
    /**
     * Creates a new Release instance.
     * @param {Partial<Release>} [$$source = {}] - The source object to create the Release.
     */
    constructor($$source = {}) {
        if (!("tag_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tag_name"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("body" in $$source)) {
            /**
             * Changelog
             * @member
             * @type {string}
             */
            this["body"] = "";
        }
        if (!("published_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["published_at"] = "";
        }
        if (!("prerelease" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["prerelease"] = false;
        }
        if (!("assets" in $$source)) {
            /**
             * @member
             * @type {Asset[]}
             */
            this["assets"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Release instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Release}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("assets" in $$parsedSource) {
            $$parsedSource["assets"] = $$createField5_0($$parsedSource["assets"]);
        }
        return new Release(/** @type {Partial<Release>} */($$parsedSource));
    }
}

/**
 * UpdateInfo contains update check result
 */
export class UpdateInfo {
    /**
     * Creates a new UpdateInfo instance.
     * @param {Partial<UpdateInfo>} [$$source = {}] - The source object to create the UpdateInfo.
     */
    constructor($$source = {}) {
        if (!("available" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["available"] = false;
        }
        if (!("currentVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["currentVersion"] = "";
        }
        if (!("latestVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["latestVersion"] = "";
        }
        if (!("changelog" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["changelog"] = "";
        }
        if (!("downloadUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["downloadUrl"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateInfo(/** @type {Partial<UpdateInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Asset.createFrom;
const $$createType1 = $Create.Array($$createType0);
