// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * RoadmapItem represents a single feature or task in the roadmap (frontend contract)
 */
export class RoadmapItem {
    /**
     * Creates a new RoadmapItem instance.
     * @param {Partial<RoadmapItem>} [$$source = {}] - The source object to create the RoadmapItem.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["friendly_title"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["title_i18n"] = undefined;
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {Status}
             */
            this["status"] = Status.$zero;
        }
        if (!("votes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["votes"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["votes_up"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["votes_down"] = undefined;
        }
        if (!("comments" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["comments"] = 0;
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("labels" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["labels"] = [];
        }
        if (!("author" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["author"] = "";
        }
        if (!("author_avatar" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["author_avatar"] = "";
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["shipped_at"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RoadmapItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RoadmapItem}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        const $$createField11_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("title_i18n" in $$parsedSource) {
            $$parsedSource["title_i18n"] = $$createField3_0($$parsedSource["title_i18n"]);
        }
        if ("labels" in $$parsedSource) {
            $$parsedSource["labels"] = $$createField11_0($$parsedSource["labels"]);
        }
        return new RoadmapItem(/** @type {Partial<RoadmapItem>} */($$parsedSource));
    }
}

/**
 * Status represents the state of a roadmap item
 * @readonly
 * @enum {string}
 */
export const Status = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    StatusIdeia: "idea",
    StatusPlanned: "planned",
    StatusInProgress: "in-progress",
    StatusShipped: "shipped",
};

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Array($Create.Any);
