// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {launcher} from '../models';
import {updater} from '../models';
import {youtube} from '../models';

export function CheckDependencies():Promise<Array<launcher.DependencyStatus>>;

export function CheckForUpdate():Promise<updater.UpdateInfo>;

export function Download(arg1:youtube.DownloadOptions):Promise<void>;

export function DownloadAndApplyUpdate(arg1:string):Promise<void>;

export function DownloadDependencies():Promise<void>;

export function GetDownloadsPath():Promise<string>;

export function GetVersion():Promise<string>;

export function GetVideoInfo(arg1:string):Promise<youtube.VideoInfo>;

export function NeedsDependencies():Promise<boolean>;

export function RestartApp():Promise<void>;
