// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddToQueue(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddToQueue'](arg1, arg2, arg3);
}

export function AddToQueueAdvanced(arg1) {
  return window['go']['main']['App']['AddToQueueAdvanced'](arg1);
}

export function CancelDownload(arg1) {
  return window['go']['main']['App']['CancelDownload'](arg1);
}

export function CheckAria2cStatus() {
  return window['go']['main']['App']['CheckAria2cStatus']();
}

export function CheckDependencies() {
  return window['go']['main']['App']['CheckDependencies']();
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ClearDownloadHistory() {
  return window['go']['main']['App']['ClearDownloadHistory']();
}

export function CompressImage(arg1, arg2) {
  return window['go']['main']['App']['CompressImage'](arg1, arg2);
}

export function CompressVideo(arg1, arg2, arg3) {
  return window['go']['main']['App']['CompressVideo'](arg1, arg2, arg3);
}

export function ConvertImage(arg1) {
  return window['go']['main']['App']['ConvertImage'](arg1);
}

export function ConvertVideo(arg1) {
  return window['go']['main']['App']['ConvertVideo'](arg1);
}

export function DeleteAria2c() {
  return window['go']['main']['App']['DeleteAria2c']();
}

export function Download(arg1) {
  return window['go']['main']['App']['Download'](arg1);
}

export function DownloadAndApplyUpdate(arg1) {
  return window['go']['main']['App']['DownloadAndApplyUpdate'](arg1);
}

export function DownloadAria2c() {
  return window['go']['main']['App']['DownloadAria2c']();
}

export function DownloadDependencies() {
  return window['go']['main']['App']['DownloadDependencies']();
}

export function DownloadImage(arg1, arg2) {
  return window['go']['main']['App']['DownloadImage'](arg1, arg2);
}

export function ExtractAudio(arg1) {
  return window['go']['main']['App']['ExtractAudio'](arg1);
}

export function GetAvailableAppVersions() {
  return window['go']['main']['App']['GetAvailableAppVersions']();
}

export function GetDownloadHistory(arg1) {
  return window['go']['main']['App']['GetDownloadHistory'](arg1);
}

export function GetDownloadQueue() {
  return window['go']['main']['App']['GetDownloadQueue']();
}

export function GetDownloadsPath() {
  return window['go']['main']['App']['GetDownloadsPath']();
}

export function GetGitHubToken() {
  return window['go']['main']['App']['GetGitHubToken']();
}

export function GetImageDownloadPath() {
  return window['go']['main']['App']['GetImageDownloadPath']();
}

export function GetImageInfo(arg1) {
  return window['go']['main']['App']['GetImageInfo'](arg1);
}

export function GetInstagramCarousel(arg1) {
  return window['go']['main']['App']['GetInstagramCarousel'](arg1);
}

export function GetRoadmap(arg1) {
  return window['go']['main']['App']['GetRoadmap'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function GetVideoDownloadPath() {
  return window['go']['main']['App']['GetVideoDownloadPath']();
}

export function GetVideoInfo(arg1) {
  return window['go']['main']['App']['GetVideoInfo'](arg1);
}

export function InstallAppVersion(arg1) {
  return window['go']['main']['App']['InstallAppVersion'](arg1);
}

export function LogoutGitHub() {
  return window['go']['main']['App']['LogoutGitHub']();
}

export function NeedsDependencies() {
  return window['go']['main']['App']['NeedsDependencies']();
}

export function OpenDownloadFolder(arg1) {
  return window['go']['main']['App']['OpenDownloadFolder'](arg1);
}

export function OpenUrl(arg1) {
  return window['go']['main']['App']['OpenUrl'](arg1);
}

export function PollGitHubAuth(arg1) {
  return window['go']['main']['App']['PollGitHubAuth'](arg1);
}

export function RestartApp() {
  return window['go']['main']['App']['RestartApp']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectImageDirectory() {
  return window['go']['main']['App']['SelectImageDirectory']();
}

export function SelectImageFile() {
  return window['go']['main']['App']['SelectImageFile']();
}

export function SelectOutputDirectory() {
  return window['go']['main']['App']['SelectOutputDirectory']();
}

export function SelectVideoDirectory() {
  return window['go']['main']['App']['SelectVideoDirectory']();
}

export function SelectVideoFile() {
  return window['go']['main']['App']['SelectVideoFile']();
}

export function SetClipboardMonitor(arg1) {
  return window['go']['main']['App']['SetClipboardMonitor'](arg1);
}

export function StartGitHubAuth() {
  return window['go']['main']['App']['StartGitHubAuth']();
}

export function SuggestFeature(arg1, arg2) {
  return window['go']['main']['App']['SuggestFeature'](arg1, arg2);
}

export function UpdateYtDlp(arg1) {
  return window['go']['main']['App']['UpdateYtDlp'](arg1);
}

export function VoteDownFeature(arg1) {
  return window['go']['main']['App']['VoteDownFeature'](arg1);
}

export function VoteFeature(arg1) {
  return window['go']['main']['App']['VoteFeature'](arg1);
}
