// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {storage} from '../models';
import {youtube} from '../models';
import {handlers} from '../models';
import {launcher} from '../models';
import {updater} from '../models';
import {images} from '../models';
import {roadmap} from '../models';
import {config} from '../models';
import {auth} from '../models';

export function AddToQueue(arg1:string,arg2:string,arg3:boolean):Promise<storage.Download>;

export function AddToQueueAdvanced(arg1:youtube.DownloadOptions):Promise<storage.Download>;

export function CancelDownload(arg1:string):Promise<void>;

export function CheckAria2cStatus():Promise<handlers.Aria2cStatus>;

export function CheckDependencies():Promise<Array<launcher.DependencyStatus>>;

export function CheckForUpdate():Promise<updater.UpdateInfo>;

export function ClearDownloadHistory():Promise<void>;

export function CompressImage(arg1:string,arg2:number):Promise<handlers.ConversionResult>;

export function CompressVideo(arg1:string,arg2:string,arg3:string):Promise<handlers.ConversionResult>;

export function ConvertImage(arg1:handlers.ImageConvertRequest):Promise<handlers.ConversionResult>;

export function ConvertVideo(arg1:handlers.VideoConvertRequest):Promise<handlers.ConversionResult>;

export function DeleteAria2c():Promise<void>;

export function Download(arg1:youtube.DownloadOptions):Promise<void>;

export function DownloadAndApplyUpdate(arg1:string):Promise<void>;

export function DownloadAria2c():Promise<void>;

export function DownloadDependencies():Promise<void>;

export function DownloadImage(arg1:string,arg2:string):Promise<string>;

export function ExtractAudio(arg1:handlers.AudioExtractRequest):Promise<handlers.ConversionResult>;

export function GetAvailableAppVersions():Promise<Array<updater.Release>>;

export function GetDownloadHistory(arg1:number):Promise<Array<storage.Download>>;

export function GetDownloadQueue():Promise<Array<storage.Download>>;

export function GetDownloadsPath():Promise<string>;

export function GetGitHubToken():Promise<string>;

export function GetImageDownloadPath():Promise<string>;

export function GetImageInfo(arg1:string):Promise<images.ImageInfo>;

export function GetInstagramCarousel(arg1:string):Promise<handlers.MediaInfo>;

export function GetRoadmap(arg1:string):Promise<Array<roadmap.RoadmapItem>>;

export function GetSettings():Promise<config.Config>;

export function GetVersion():Promise<string>;

export function GetVideoDownloadPath():Promise<string>;

export function GetVideoInfo(arg1:string):Promise<youtube.VideoInfo>;

export function InstallAppVersion(arg1:string):Promise<void>;

export function LogoutGitHub():Promise<void>;

export function NeedsDependencies():Promise<boolean>;

export function OpenDownloadFolder(arg1:string):Promise<void>;

export function OpenUrl(arg1:string):Promise<void>;

export function PollGitHubAuth(arg1:string):Promise<string>;

export function RestartApp():Promise<void>;

export function SaveSettings(arg1:config.Config):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SelectImageDirectory():Promise<string>;

export function SelectImageFile():Promise<string>;

export function SelectOutputDirectory():Promise<string>;

export function SelectVideoDirectory():Promise<string>;

export function SelectVideoFile():Promise<string>;

export function SetClipboardMonitor(arg1:boolean):Promise<void>;

export function StartGitHubAuth():Promise<auth.DeviceCodeResponse>;

export function SuggestFeature(arg1:string,arg2:string):Promise<void>;

export function UpdateYtDlp(arg1:string):Promise<string>;

export function VoteDownFeature(arg1:number):Promise<void>;

export function VoteFeature(arg1:number):Promise<void>;
