// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckDependencies() {
  return window['go']['main']['App']['CheckDependencies']();
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function Download(arg1) {
  return window['go']['main']['App']['Download'](arg1);
}

export function DownloadAndApplyUpdate(arg1) {
  return window['go']['main']['App']['DownloadAndApplyUpdate'](arg1);
}

export function DownloadDependencies() {
  return window['go']['main']['App']['DownloadDependencies']();
}

export function GetDownloadsPath() {
  return window['go']['main']['App']['GetDownloadsPath']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function GetVideoInfo(arg1) {
  return window['go']['main']['App']['GetVideoInfo'](arg1);
}

export function NeedsDependencies() {
  return window['go']['main']['App']['NeedsDependencies']();
}

export function RestartApp() {
  return window['go']['main']['App']['RestartApp']();
}
